#!/usr/bin/env python3

from argparse import ArgumentParser
import re
from os.path import basename


def main(args):
    fastq_basename = basename(args.fastq)

    valid_fastq_name = re.compile(
        r".*(S[0-9]+_L[0-9]{3}_[IR][1-3]_[0-9]{3}\.(fastq|fq)(\.gz|))$"
    )

    # Extract what we can from the fastq name
    sample = re.search(r"[_.](S[0-9]+)[_.]", fastq_basename)
    lane = re.search(r"[_.](L[0-9]{3})[_.]", fastq_basename)
    read = re.search(r"[_.]([IR][1-3])[_.]", fastq_basename)
    extension = re.search(r"(\.(fastq|fq)(\.gz|))$", fastq_basename)

    prefix = fastq_basename[:sample.start()]
    sample = sample.group(1)
    lane = lane.group(1)
    read = read.group(1)
    extension = extension.group(1)

    if sample and lane and read and extension:
        print(
            f"[SUCCEEDED]\nSample: {sample}\nLane: {lane}\nRead: {read}\nExtension: {extension}"
        )
        print(f"Input FASTQ basename: {fastq_basename}")
        print(f"Inferred FASTQ basename: {prefix}_{sample}_{lane}_{read}_001{extension}")
    else:
        raise SystemExit(f"[FAILED]\nCould not infer all sample, lane, read, and extension for {fastq_basename}")


if __name__ == "__main__":
    parser = ArgumentParser(
        "Check a FASTQ basename to the format required by tools like cellranger (<sample>_S[0-9]+_L[0-9][0-9][0-9]_[IR][1-3]_[0-9][0-9][0-9])"
    )

    parser.add_argument(
        "-f",
        "--fastq",
        type=str,
        required=True,
        help="Path to fastq"
    )

    args = parser.parse_args()

    main(args)
