#!/usr/bin/env python3

from argparse import ArgumentParser
import re
from os.path import basename, dirname, join
from glob import glob


def main(args):
    fastq_basename = basename(args.fastq)
    fastq_dir = dirname(args.fastq)
    sample_id = args.sample_id

    valid_fastq_name = re.compile(
        r".*(S[0-9]+_L[0-9]{3}_[IR][1-3]_[0-9]{3}\.(fastq|fq)(\.gz|))$"
    )

    if re.search(valid_fastq_name, fastq_basename):
        renamed = re.sub(valid_fastq_name, rf"{sample_id}_\1", fastq_basename)
    else:
        # Extract what we can from the fastq name
        sample = re.search(r"[_.](S[0-9]+)[_.]", fastq_basename)
        lane = re.search(r"[_.](L[0-9]{3})[_.]", fastq_basename)
        read = re.search(r"[_.]([IR][1-3])[_.]", fastq_basename)
        extension = re.search(r"(\.(fastq|fq)(\.gz|))$", fastq_basename)

        sample = sample.group(1) if sample else "S1"
        lane = lane.group(1) if lane else "L001"
        if not read:
            raise SystemExit(
                f"Failed to infer read or invalid read ([R1, R2, I1, I2]) for fastq {fastq_basename}"
            )
        else:
            read = read.group(1)
        if not extension:
            raise SystemExit(
                f"Failed to infer extension or invalid extension for fastq {fastq_basename}"
            )
        else:
            extension = extension.group(1)

        renamed = f"{sample_id}_{sample}_{lane}_{read}_001{extension}"

    # Auto-detect R3 files and apply swap logic
    ## If sample has R1, R2, R3, I1 then R3 -> R2, and R2 -> I2
    ## If sample has R1, R2, R3 then R3 -> R2, and R2 -> I1
    sample_match = re.search(r"(S[0-9]+)", fastq_basename)
    lane_match = re.search(r"(L[0-9]{3})", fastq_basename)

    if sample_match and lane_match:
        sample_num = sample_match.group(1)
        lane_num = lane_match.group(1)
        
        # Check for presence of each read type
        r1_pattern = join(fastq_dir, f"*{sample_num}*{lane_num}*R1*.fastq*")
        r2_pattern = join(fastq_dir, f"*{sample_num}*{lane_num}*R2*.fastq*")
        r3_pattern = join(fastq_dir, f"*{sample_num}*{lane_num}*R3*.fastq*")
        i1_pattern = join(fastq_dir, f"*{sample_num}*{lane_num}*I1*.fastq*")
        
        has_r1 = bool(glob(r1_pattern))
        has_r2 = bool(glob(r2_pattern))
        has_r3 = bool(glob(r3_pattern))
        has_i1 = bool(glob(i1_pattern))
        
        # Only apply renaming if we have R3
        if has_r3:
            # R3 becomes R2
            if "_R3_" in renamed:
                renamed = renamed.replace("_R3_", "_R2_")
            # R2 becomes I1 (if no I1) or I2 (if I1 exists)
            elif "_R2_" in renamed:
                if has_i1:
                    renamed = renamed.replace("_R2_", "_I2_")
                else:
                    renamed = renamed.replace("_R2_", "_I1_")

    print(renamed)
    

if __name__ == "__main__":
    parser = ArgumentParser(
        "Convert a FASTQ basename to the format required by cellranger (<sample>_S[0-9]+_L[0-9][0-9][0-9]_[IR][13]_[0-9][0-9][0-9])"
    )

    parser.add_argument("-f", "--fastq", type=str, required=True, help="Path to fastq")
    parser.add_argument("-s", "--sample-id", type=str, required=True, help="Sample ID")

    args = parser.parse_args()
    main(args)
