#!/usr/bin/env python3

import argparse
import polars as pl
import snapatac2 as snap


def call_peaks(
    adata: snap.AnnData, groupby: str
):
    if groupby not in adata.obs[:].columns:
        raise ValueError(f"'{groupby}' not found in adata.obs")
    print(f"Calling peaks by {groupby} and setting replicate as 'sample'...")
    snap.tl.macs3(adata, groupby=groupby, replicate="sample")
    merged_peaks = snap.tl.merge_peaks(adata.uns["macs3"], chrom_sizes=snap.genome.hg38)
    print(f"Merged peaks dim:")
    merged_peaks.shape

    adata.uns["merged_peaks"] = merged_peaks

    peaks_matrix = snap.pp.make_peak_matrix(adata, use_rep=merged_peaks['Peaks'])

    return adata, merged_peaks, peaks_matrix


def main(args):
    adata = snap.read(args.adata_input)
    adata_peaks, merged_peaks_df, adata_peaks_matrix = call_peaks(adata, args.macs3_groupby)

    adata_peaks.write(
        filename=args.adata_output
    )
    print(f"Wrote {args.adata_output}")

    merged_peaks_csv = f"{args.output_prefix}.merged_peaks.csv"
    merged_peaks_df.write_csv(
        merged_peaks_csv
    )
    print(f"Wrote {merged_peaks_csv}")

    adata_peaks_matrix_out = f"{args.output_prefix}.merged_peaks_matrix.h5ad"
    adata_peaks_matrix.write(
        filename=adata_peaks_matrix_out
    )
    print(f"Wrote {adata_peaks_matrix_out}")

    if adata_peaks.isbacked:
        adata_peaks.close()


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Peak calling with MACS3 to identify accessible chromatin regions"
    )
    parser.add_argument(
        "-g",
        "--macs3-groupby",
        type=str,
        required=True,
        help="SnapATAC2 MACS3 groupby flag (e.g. leiden)"
    )
    parser.add_argument(
        "-a",
        "--adata-input",
        type=str,
        required=True,
        help="AnnData object for a dataset"
    )
    parser.add_argument(
        "-p",
        "--output-prefix",
        type=str,
        required=True,
        help="Prefix used to name output files (i.e. merged peaks csv file and peaks matrix AnnData object)"
    )
    parser.add_argument(
        "-o",
        "--adata-output",
        type=str,
        required=True,
        help="Output file name for saving the AnnData object"
    )

    args = parser.parse_args()

    main(args)
