#!/usr/bin/env python3

import argparse
import snapatac2 as snap


def add_metadata(
    adata: snap.AnnData,
    team_id: str,
    dataset_id: str,
    source_subject_id: str,
    subject_id: str,
    sample_id: str,
    pool_id: str,
    batch: str
):
    print("Adding metadata to demultiplexed sample-level AnnData object")
    adata.obs["source_subject"] = source_subject_id
    adata.obs["subject"] = subject_id
    adata.obs["sample"] = sample_id
    adata.obs["pool"] = pool_id
    adata.obs["batch"] = batch
    adata.obs["team"] = team_id
    adata.obs["dataset"] = dataset_id
    adata.obs["batch_id"] = f"{team_id}_{dataset_id}_{pool_id}"

    return adata


def main(args):
    # This computes basic QC metrics like the number of unique fragments per cell, fraction of duplicated reads and fraction of mitochondrial read 
    adata = snap.pp.import_fragments(
        fragment_file=args.cellranger_atac_sample_split_fragments,
        chrom_sizes=snap.genome.hg38,
        sorted_by_barcode=False
    )
    adata = add_metadata(
        adata,
        args.team_id,
        args.dataset_id,
        args.source_subject_id,
        args.subject_id,
        args.sample_id,
        args.pool_id,
        args.batch
    )

    # Compute scores and add vars to in-memory AnnData
    snap.metrics.tsse(adata, snap.genome.hg38)
    snap.pp.add_tile_matrix(adata, bin_size=500)

    adata.write(
        filename=args.adata_output
    )
    print(f"Wrote {args.adata_output}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Convert demultiplexed sample-level Cell Ranger ATAC counts to AnnData objects"
    )
    parser.add_argument(
        "-f",
        "--cellranger-atac-sample-split-fragments",
        type=str,
        required=True,
        help="The demultiplexed sample-level Cell Ranger ATAC fragments.tsv.gz output that is the barcoded and aligned fragment file"
    )
    parser.add_argument(
        "-t",
        "--team-id",
        type=str,
        required=True,
        help="CRN Team ID"
    )
    parser.add_argument(
        "-d",
        "--dataset-id",
        type=str,
        required=True,
        help="ASAP dataset ID"
    )
    parser.add_argument(
        "-a",
        "--source-subject-id",
        type=str,
        required=True,
        help="Source subject/donor ID"
    )
    parser.add_argument(
        "-c",
        "--subject-id",
        type=str,
        required=True,
        help="ASAP subject/donor ID"
    )
    parser.add_argument(
        "-s",
        "--sample-id",
        type=str,
        required=True,
        help="ASAP sample ID"
    )
    parser.add_argument(
        "-p",
        "--pool-id",
        type=str,
        required=True,
        help="Source pool ID used to construct 'batch_id'"
    )
    parser.add_argument(
        "-b",
        "--batch",
        type=str,
        required=True,
        help="ASAP batch from which the sample/dataset originated"
    )
    parser.add_argument(
        "-o",
        "--adata-output",
        type=str,
        required=True,
        help="Output file name for saving the AnnData object"
    )

    args = parser.parse_args()

    main(args)
