#!/usr/bin/env python3

import argparse
import snapatac2 as snap
import scanpy as sc


def magic_imputation(
    adata: snap.AnnData
):
    sc.external.pp.magic(adata, solver="approximate")

    return adata


def main(args):
    adata = snap.read(args.adata_input)
    adata_magic_imputed = magic_imputation(adata_gene_matrix)

    adata_magic_imputed_out = f"{args.output_prefix}.gene_matrix.magic_imputed.h5ad"
    adata_magic_imputed.write(
        filename=adata_magic_imputed_out
    )
    print(f"Wrote {adata_magic_imputed_out}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Smooth and impute the sparse cell by gene activity matrix using MAGIC"
    )
    parser.add_argument(
        "-a",
        "--adata-input",
        type=str,
        required=True,
        help="AnnData object for a dataset",
    )
    parser.add_argument(
        "-p",
        "--output-prefix",
        type=str,
        required=True,
        help="Prefix used to name output files (i.e. gene matrix AnnData object)"
    )

    args = parser.parse_args()

    main(args)
