#!/usr/bin/env python3

import argparse
import pandas as pd
import snapatac2 as snap
import harmonypy


def run_harmony(
    adata: snap.AnnData, batch_key: str
):
    print(f"Running Harmony integration...")
    snap.pp.harmony(
        adata,
        batch=batch_key,
        max_iter_harmony=20
    )

    return adata


def main(args):
    adata = snap.read(args.adata_input)
    adata_harmony = run_harmony(adata, args.batch_key)

    adata_harmony.write(
        filename=args.adata_output
    )
    print(f"Wrote {args.adata_output}")

    if adata_harmony.isbacked:
        adata_harmony.close()


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Integrate Harmony for batch correction"
    )
    parser.add_argument(
        "-a",
        "--adata-input",
        type=str,
        required=True,
        help="AnnData object for a dataset"
    )
    parser.add_argument(
        "-b",
        "--batch-key",
        type=str,
        required=True,
        help="Key in AnnData object for batch information"
    )
    parser.add_argument(
        "-o",
        "--adata-output",
        type=str,
        required=True,
        help="Output file name for saving the AnnData object"
    )
    
    args = parser.parse_args()

    main(args)
