#!/usr/bin/env python3

import argparse
import pandas as pd
import kaleido
import snapatac2 as snap


def qc(
    adatas: list
):
    snap.pp.filter_cells(adatas, min_counts=5000, min_tsse=10, max_counts=100000)
    adatas = [a for a in adatas if a.n_obs >= 50]
    print(f"{len(adatas)} samples remaining after cell filtering")

    snap.pp.select_features(adatas, n_features=500000)

    snap.pp.scrublet(adatas)
    snap.pp.filter_doublets(adatas)
    adatas = [a for a in adatas if a.n_obs > 0]
    print(f"{len(adatas)} samples remaining after doublet removal")

    return adatas


def plot_qc(
    merged_adata: snap.AnnData, plot_prefix: str
):
    frag_size_distr_out = f"{plot_prefix}.frag_size_distr.png"
    snap.pl.frag_size_distr(
        merged_adata,
        show=False,
        out_file=frag_size_distr_out
    )
    print(f"Wrote {frag_size_distr_out}")

    tsse_out = f"{plot_prefix}.tsse.png"
    snap.pl.tsse(
        merged_adata,
        show=False,
        out_file=tsse_out
    )
    print(f"Wrote {tsse_out}")


def main(args):
    sample_files = []
    # Note that the sample id should be the official ASAP_samples
    with open(args.adata_objects_fofn, "r") as file:
        for sample in file:
            # Check that sample line is not empty
            if sample.strip():
                columns = sample.strip().split("\t")
                sample_files.append(columns)

    print(f"Processing {len(sample_files)} samples")

    sample_names = [s[0] for s in sample_files]
    adatas = [snap.read(s[1]) for s in sample_files]

    adatas = qc(adatas)

    merged_adata = snap.concat(
        adatas,
        join="inner",
        file=args.adata_output,
    )
    print(f"Wrote {args.adata_output}")

    merged_adata.obs[:].write_csv(
        args.output_metadata
    )
    print(f"Wrote {args.output_metadata}")

    plot_qc(merged_adata, args.plot_prefix)

    merged_adata.close()


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Merge AnnData objects and calculate and plot QC metrics including tile matrices, features, and doublets"
    )
    parser.add_argument(
        "-a",
        "--adata-objects-fofn",
        type=str,
        required=True,
        help="Newline-delimited TSV of sample names and paths to the set of input adata objects (file-of-filenames)"
    )
    parser.add_argument(
        "-p",
        "--plot-prefix",
        type=str,
        required=True,
        help="Prefix used to name plots"
    )
    parser.add_argument(
        "-o",
        "--adata-output",
        type=str,
        required=True,
        help="Output file name for saving the AnnData object"
    )
    parser.add_argument(
        "-m",
        "--output-metadata",
        type=str,
        required=True,
        help="Output file name for saving the AnnData object metadata as csv file"
    )

    args = parser.parse_args()

    main(args)
