#!/usr/bin/env python3

import argparse
import anndata as ad
import pandas as pd
import kaleido
import snapatac2 as snap

# Patch that makes all pandas Series have a nonzero() method - removed after pandas 2.1+
pd.Series.nonzero = lambda self: self.to_numpy().nonzero()


def merge_adata(
    adata_objects_fofn: str, chunk_size: int = 5
):
    sample_files = []
    # Note that the sample id should be the official ASAP_samples
    with open(adata_objects_fofn, "r") as file:
        for sample in file:
            # Check that sample line is not empty
            if sample.strip():
                columns = sample.strip().split("\t")
                sample_files.append(columns)

    print(f"Processing {len(sample_files)} samples in chunks of {chunk_size}")

    merged_chunks = []

    for i in range(0, len(sample_files), chunk_size):
        chunk_files = sample_files[i:i+chunk_size]
        print(f"Processing chunk {i//chunk_size + 1}/{(len(sample_files)-1)//chunk_size + 1}")

        adatas = {}
        for sample_name, file_path in chunk_files:
            raw = snap.read(file_path, backed=None)
            adatas[sample_name] = raw

        chunk_adata = ad.concat(
            adatas, 
            merge="same", 
            uns_merge="same", 
            index_unique="_"
        )

        merged_chunks.append(chunk_adata)

        # Clean up memory
        del adatas

    # We could subset to the top_genes here before concat if we have memory issues (e.g. whole dataset harmonization)
    print("Merging all chunks...")
    merged_adata = ad.concat(
        merged_chunks,
        merge="same",
        uns_merge="same",
        index_unique="_"
    )

    return merged_adata


def compute_qc_metrics(
    merged_adata: snap.AnnData, plot_prefix: str
):
    print("Computing QC metrics...")
    # TODO - check all plots
    frag_size_distr_out = f"{plot_prefix}.frag_size_distr.png"
    snap.pl.frag_size_distr(
        merged_adata,
        show=False,
        out_file=frag_size_distr_out
    )
    print(f"Wrote {frag_size_distr_out}")

    snap.metrics.tsse(merged_adata, snap.genome.hg38)
    tsse_out = f"{plot_prefix}.tsse.png"
    snap.pl.tsse(
        merged_adata,
        show=False,
        out_file=tsse_out
    )
    print(f"Wrote {tsse_out}")

    snap.pp.filter_cells(merged_adata, min_tsse=7)
    # snap.pp.filter_cells(merged_adata, min_counts=5000, min_tsse=10, max_counts=100000)

    snap.pp.add_tile_matrix(merged_adata, bin_size=5000)
    snap.pp.select_features(merged_adata, n_features=50000)

    snap.pp.scrublet(merged_adata)
    snap.pp.filter_doublets(merged_adata)

    return merged_adata


def main(args):
    adatas = merge_adata(args.adata_objects_fofn)
    adatas_qc = compute_qc_metrics(adatas, args.plot_prefix)

    adatas_qc.write(
        filename=args.adata_output
    )
    print(f"Wrote {args.adata_output}")

    adatas_qc.obs.to_csv(
        args.output_metadata,
        index=True
    )
    print(f"Wrote {args.output_metadata}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Merge AnnData objects and calculate and plot QC metrics including tile matrices, features, and doublets"
    )
    parser.add_argument(
        "-a",
        "--adata-objects-fofn",
        type=str,
        required=True,
        help="Newline-delimited TSV of sample names and paths to the set of input adata objects (file-of-filenames)"
    )
    parser.add_argument(
        "-p",
        "--plot-prefix",
        type=str,
        required=True,
        help="Prefix used to name plots"
    )
    parser.add_argument(
        "-o",
        "--adata-output",
        type=str,
        required=True,
        help="Output file name for saving the AnnData object"
    )
    parser.add_argument(
        "-m",
        "--output-metadata",
        type=str,
        required=True,
        help="Output file name for saving the AnnData object metadata as csv file"
    )

    args = parser.parse_args()

    main(args)
